### ISSUE TITLE
SyntaxError: broken PNG file (chunk b'\x00\x00\x00\x00')

### ISSUE THREAD

**Issue by joker5743** [shachoi/HANet#1]
When I reshow this program, the system show this question. Is the memory lack？I use 1 pascal with 16GB to train. Is that enough?
![第一次崩溃2](https://user-images.githubusercontent.com/46232881/82433109-8f32e900-9ac3-11ea-9f25-d1d43899cff1.PNG)

It work well in epoch0, but crash at epoch1.

**Comment by sunghac** [comment]
Hi, thank you for your attention to our project.
If you want to train with "./script/train_r101_os8_hanet.sh" script, two Titan RTX (2 X 24GB) gpus are required. The script file specifies 2 gpus and 4 batch size per single gpu (totally 8 batch).
However, the above error messages aren't related to the gpu memory size. Perhaps you modified the batch size.

It seems like some png file has a problem.
How about inserting the print code above 649 line to find out which png file has the problem?

![image](https://user-images.githubusercontent.com/34509882/82443923-50119180-9add-11ea-9652-19aeffea9891.png)

Due to class uniform sampling, different images can be loaded every epoch.

**Comment by joker5743** [comment]
> Hi, thank you for your attention to our project.
> If you want to train with "./script/train_r101_os8_hanet.sh" script, two Titan RTX (2 X 24GB) gpus are required. The script file specifies 2 gpus and 4 batch size per single gpu (totally 8 batch).
> However, the above error messages aren't related to the gpu memory size. Perhaps you modified the batch size.
> 
> It seems like some png file has a problem.
> How about inserting the print code above 649 line to find out which png file has the problem?
> 
> ![image](https://user-images.githubusercontent.com/34509882/82443923-50119180-9add-11ea-9652-19aeffea9891.png)
> 
> Due to class uniform sampling, different images can be loaded every epoch.

I modify the batch size to 2, because I have only 1 Pascal with 16GB. But when I modify the max_epoch to 1 not 180. It work well, I guess it's not the data reanson.

**Comment by sunghac** [comment]
As I mentioned, not all png files are loaded every epoch in the class uniform sampling setting.  So every epoch, the file that causes the problem can be included randomly.

**Comment by yhwyaaa** [comment]
> When I reshow this program, the system show this question. Is the memory lack？I use 1 pascal with 16GB to train. Is that enough? ![第一次崩溃2](https://user-images.githubusercontent.com/46232881/82433109-8f32e900-9ac3-11ea-9f25-d1d43899cff1.PNG)
> 
> It work well in epoch0, but crash at epoch1.


Thank you for your excellent work. Hello, could you please let me know how you solved this issue? I modified the batch size, when the batchsize = 1, the same issue occurs after training for 5 epochs. When the batchsize = 4, training cannot proceed. I look forward to your response.
